version: '3.9'

services:
  front:
    image: front:0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    depends_on:
      - api
    networks:
      - first-network
  api:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: api:0.0.1-SNAPSHOT
    ports:
      - 9000:9000
    networks:
      - first-network

networks:
  first-network:
#    driver: bridge
#  second-network:
#    driver: bridge
