version: '3.9'

services:
  front:
    image: front:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - api
    networks:
      - hr-employees-network
  api:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: api:0.0.1-SNAPSHOT
    ports:
      - 9000:9000
    networks:
      - hr-employees-network

networks:
  hr-employees-network:
